Multinomial Logistic regression

In [46]:
import pandas as pd

col_names = [
    "name",
    "position",
    "number_of_maps",
    "firepower",
    "entrying",
    "trading",
    "opening",
    "clutching",
    "sniping",
    "utility",
]

data = pd.read_csv("./Training_Data.csv")
data.head()

,name,position,number_of_maps,firepower,entrying,trading,opening,clutching,sniping,utility,igl
0,alex666,Closer,83,27,44,43,26,58,0,61,1
1,npl,Opener,83,85,44,60,76,47,0,48,0
2,kensizor,Opener,83,70,94,56,63,37,0,41,0
3,esenthial,Linchpin,83,31,40,79,22,61,0,23,0
4,s1zzi,AWPer,83,57,47,32,77,63,93,33,0

In [47]:
for col in [
    "firepower",
    "entrying",
    "trading",
    "opening",
    "clutching",
    "sniping",
    "utility",
]:
    data[col] = data[col] / 100

data.head()

,name,position,number_of_maps,firepower,entrying,trading,opening,clutching,sniping,utility,igl
0,alex666,Closer,83,0.27,0.44,0.43,0.26,0.58,0.00,0.61,1
1,npl,Opener,83,0.85,0.44,0.60,0.76,0.47,0.00,0.48,0
2,kensizor,Opener,83,0.70,0.94,0.56,0.63,0.37,0.00,0.41,0
3,esenthial,Linchpin,83,0.31,0.40,0.79,0.22,0.61,0.00,0.23,0
4,s1zzi,AWPer,83,0.57,0.47,0.32,0.77,0.63,0.93,0.33,0

In [62]:
feature_cols = [
    "firepower",
    "entrying",
    "trading",
    "opening",
    "clutching",
    "sniping",
    "utility",
]
train_data = data.loc[data["igl"] == 0]

train_data.head()

,name,position,number_of_maps,firepower,entrying,trading,opening,clutching,sniping,utility,igl
1,npl,Opener,83,0.85,0.44,0.60,0.76,0.47,0.00,0.48,0
2,kensizor,Opener,83,0.70,0.94,0.56,0.63,0.37,0.00,0.41,0
3,esenthial,Linchpin,83,0.31,0.40,0.79,0.22,0.61,0.00,0.23,0
4,s1zzi,AWPer,83,0.57,0.47,0.32,0.77,0.63,0.93,0.33,0
5,Magnojez,Opener,67,0.88,0.42,0.32,0.85,0.47,0.03,0.82,0

In [64]:
X = train_data[feature_cols]
Y = train_data[["position", "number_of_maps"]]

Y.head()

   position  number_of_maps
1    Opener              83
2    Opener              83
3  Linchpin              83
4     AWPer              83
5    Opener              67

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.25, random_state=16
)

In [66]:
import numpy as np
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(random_state=16)

sample_weight = np.sqrt(Y_train["number_of_maps"])

clf = logreg.fit(X_train, Y_train["position"], sample_weight)

y_pred = clf.predict(X_test)

In [67]:
from sklearn.metrics import classification_report

target_names = ["AWPer", "Opener", "Closer", "Linchpin"]

print(classification_report(Y_test["position"], y_pred, target_names=target_names))

              precision    recall  f1-score   support

       AWPer       1.00      1.00      1.00         6
      Opener       0.25      0.25      0.25         4
      Closer       0.40      0.29      0.33         7
    Linchpin       0.57      0.80      0.67         5

    accuracy                           0.59        22
   macro avg       0.56      0.58      0.56        22
weighted avg       0.58      0.59      0.58        22

In [68]:
print(logreg.predict(np.array([0.7, 0.2, 0.5, 0.2, 0.6, 0.9, 0.4]).reshape(1, -1)))

['AWPer']

/home/archie955/cs2/server/.venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [69]:
print(clf.coef_, clf.intercept_)

# in order: AWPer, Closer, Linchpin, Opener
# features: ["firepower", "entrying", "trading", "opening", "clutching", "sniping", "utility"]

[[-0.44355846 -1.34300109  0.63636852 -0.22090896  0.67330259  5.14500771
   0.45028701]
 [ 0.10257542 -0.82142701  0.02528448 -1.07656664  2.11496055 -2.1498716
   0.33118296]
 [-1.32327287 -0.0793995   0.04368472 -2.93517855 -0.14881964 -1.78801245
  -1.88524563]
 [ 1.66425591  2.2438276  -0.70533772  4.23265416 -2.63944351 -1.20712365
   1.10377565]] [-1.56537799  0.56983244  3.95253081 -2.95698526]

In [70]:
print(clf.classes_)

['AWPer' 'Closer' 'Linchpin' 'Opener']

In [71]:
print(clf.feature_names_in_)

['firepower' 'entrying' 'trading' 'opening' 'clutching' 'sniping'
 'utility']